name: workflow-1
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Install-Dependencies:
    runs-on: ubuntu-latest
#    needs: Code-Checkout
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js env
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm ci

    - name: Upload node_modules
      uses: actions/upload-artifact@v4
      with:
        name: npm_ci-dependencies
        path: node_modules 

  Linting-Stage:
    runs-on: ubuntu-latest
    needs: Install-Dependencies
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js env
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Download node_modules
      uses: actions/download-artifact@v3
      with:
        name: npm_ci-dependencies
          
    - name: Run Lint
      run: npm run lint

  Testing-Stage:
    runs-on: ubuntu-latest
    needs: Linting-Stage
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js env
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Download node_modules
      uses: actions/download-artifact@v3
      with:
        name: npm_ci-dependencies

    - name: Run Tests
      run: npm run test

  Build-Stage:
    runs-on: ubuntu-latest
    needs: Testing-Stage
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js env
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Download node_modules
      uses: actions/download-artifact@v3
      with:
        name: npm_ci-dependencies

    - name: Build Stage
      run: npm run build